#+TITLE:
#+DATE:
#+AUTHOR:
#+EMAIL:
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:nil d:(not "LOGBOOK") date:nil e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+LATEX_CLASS:thesis

#+BEGIN_LaTeX
%% Use these commands to set biographic information for the title page:
\title{Enabling Novel IGRT Imaging Trajectories with Optimization-Based Reconstruction Algorithms}
\author{Andrew Davis}
\department{Committee on Medical Physics}
\division{Biological Sciences}
\degree{Ph. D.}
\date{June, 2016}

%% Use these commands to set a dedication and epigraph text
\dedication{Dedication Text}
\epigraph{Epigraph Text}

% If you don't want a title page comment out the next line and uncomment the line after it:
\maketitle
%\omittitle

% These lines can be commented out to disable the copyright/dedication/epigraph pages
\makecopyright
\makededication
\makeepigraph

%% Make the various tables of contents
\tableofcontents
\listoffigures
\listoftables

\acknowledgments
% Enter Acknowledgements here

\abstract
% Enter Abstract here

\mainmatter
% Main body of text follows
#+END_LaTeX

* notes                                      :noexport:
  :PROPERTIES:
  :ID:       7f3d97de-795e-402a-82ac-591717f86bfd
  :END:
** requirements
   :PROPERTIES:
   :ID:       931c9c50-bfaf-4c8e-b2cc-bcfdf62e327d
   :END:

- [[http://www.lib.uchicago.edu/e/phd/][uchicago]] dissertation guide
- [[https://github.com/zuwiki/ucetd-latex][uoc thesis]] template

* Introduction
  :PROPERTIES:
  :ID:       852796c3-9a3b-49da-bc08-1299e93e0768
  :END:
** Background: Computed Tomography
   :PROPERTIES:
   :ID:       898c8a79-a3b0-4cb2-b1be-2838c8b86426
   :END:
*** Analytic-Based Reconstruction
    :PROPERTIES:
    :ID:       20c14d08-7649-4644-b616-e86e0b7cc515
    :END:
In the 1980s, a lot of work was done to directly solve the inverse
problem for the cone-beam geometry. By modeling the projection
formation process as a Radon transform or an X-ray transform,
reconstruction algorithms were formulated by finding an analytic-based
inverse to the transform. However, for the inverse to be exact, it
needed to meet strict requirements such as Tuy's condition which
states that every plane through the object must intersect the source
trajectory cite:tuy_inversion_1983. While some exceptions to this
requirement were found, it demonstrates the strict requirements on the
types of scanning trajectories for which an exact inverse could be
found.

The circular scanning trajectory that is ubiquitous in the clinic for
CBCT is one trajectory that fails to meet Tuy's condition. The most
popular reconstruction algorithm for the circular CBCT trajectory is
the filtered-backprojection (FBP) algorithm proposed by Feldkamp,
Davis, and Kress (FDK) cite:feldkamp_practical_1984 which is still the
industry standard. FDK is only an exact inversion to the Radon
transform on the midplane containing the circular source
trajectory. For transaxial planes other than the midplane, a
quasi-redundancy in the scanning data is assumed. It is the violation
of this assumption which leads to cone-angle artifacts. These
artifacts become more severe at larger cone angles where this
assumption is less applicable.

The presence of cone-angle artifacts in FDK reconstructions from the
incomplete data acquired with circular scanning trajectories led to
research into inverse algorithms for cone-beam scans from
theoretically complete trajectories such as a circle plus a line
cite:zeng_cone-beam_1992. It became apparent in the reconstruction
results that implementing these direct reconstruction algorithms did
not produce the anticipated results cite:kudo_derivation_1994. Severe
artifacts and numerical errors were found in the reconstructions due
to factors such as truncation introducing high-frequency components
that are amplified in the filtration process.

*** Optimization-Based Reconstruction
    :PROPERTIES:
    :ID:       07e91084-61be-43d3-a905-65ef0ab997a4
    :END:
Analytic-based reconstruction algorithms are formulated by explicitly
finding an inverse to the X-ray transform
#+BEGIN_LaTeX
  \begin{equation}
    \label{eq:xray}
    g(\mathbf{r}_0,\hat{\theta})=\int_0^{\infty}f(\mathbf{r}_0+t\hat{\theta})dt,
  \end{equation}
#+END_LaTeX
where the data function $g$ is acquired by integrating along the ray
from the source at $\mathbf{r}_0$ in the direction $\hat{\theta}$ through
the object function $f$. A fundamental problem with these
reconstruction algorithms when practically reconstructing $f$ is the
assumption of a continuous-to-continuous (CC) model. These
analytic-based reconstruction algorithms impose dense sampling
requirements for both the detector and number of views to approximate
a continuous data function. Given that the data function from the
digital detector and the numerical array for storing the reconstructed
image are both discrete, a more natural approach to the inverse
problem would be a discrete-to-discrete (DD) imaging model
cite:barrett_foundations_2003.

Iterative reconstruction algorithms are more robust because they do
implement a more accurate DD model of the imaging system. The X-ray
transform of the object function can be represented as the linear
system
#+BEGIN_LaTeX
  \begin{equation}
    \label{eq:ddsys}
    \mathbf{g}=\mathcal{H}\mathbf{f},
  \end{equation}
#+END_LaTeX
where $\mathbf{g}$ is the discrete $M$ pixel sampled projection on the
detector, $\mathcal{H}$ is the $M\times N$ discrete form of the X-ray
transform, and $\mathbf{f}$ is the object function represented on a N
voxel basis. As direct inversion of $\mathcal{H}$ is impractical due
to both its size and inconsistencies from factors such as noise,
optimization techniques are used to solve this system for an estimate
of the object $\widetilde{\mathbf{f}}$.

The optimization problem for these iterative reconstruction algorithms
is formulated as an objective function based on the actual data
$\mathbf{g}$ and the image model $\mathcal{H}\mathbf{f}$. An
optimization algorithm is then used to iteratively update the estimate
of $\widetilde{\mathbf{f}}$ until a suitable convergence criterion has
been met. The parameters of the optimization problem, the optimization
algorithm, and the convergence criteria are all important factors in
determining the properties of the reconstructed image and subsequently
its utility.

Two optimization-based reconstruction methods we will use with these
non-circular trajectories are maximum-likelihood expectation
maximization (MLEM) cite:shepp_maximum_1982,dempster_maximum_1977 and
constrained, total-variation (TV) minimization by adaptive steepest
descent-projection onto convex sets (ASD-POCS)
cite:sidky_image_2008. Previous work has shown that these iterative
algorithms are able to reconstruct clinically useful images under
scanning conditions for which analytic-based FDK fails
cite:han_optimization-based_2012,sidky_image_2007,sidky_accurate_2006. The
reconstruction work from sparse-view data cite:bian_evaluation_2010
alone suggests that views could be distributed at different axial
positions to acquire additional scan information without imparting
more dose than the dense set of angular views used in current clinical
circular scans with analytic-based reconstruction.

** Background: Scanning Trajectories
   :PROPERTIES:
   :ID:       c90cd638-44e6-49f3-9283-29f75d163005
   :END:
*** Standard Trajectories
    :PROPERTIES:
    :ID:       6293da29-e448-4614-84b6-065af1cc6be9
    :END:

In IGRT, linac-mounted CBCT imaging systems such as Varian's OBI now
routinely provide patient image information. These images are used to
check the patient alignment before delivering the radiation
treatment. The circular rotation of the linac gantry defines the
acquisition trajectory for the CBCT scan. While such a scanning
trajectory provides sufficient information for an analytic-based
reconstruction of the scan volume, there are a variety of limitations
that arise from this work flow.

Due to engineering and cost restrictions, the OBI detector has a
limited size. This restricts the FOV that can be imaged in a
traditional circular scan. While the offset detector technique
cite:bian_optimization-based_2013,cho_cone-beam_1995 is commonly used
to increase the transaxial FOV, the axial coverage is still very
limited cite:pearson_non-circular_2010. The reason why the limited FOV
has not been addressed by increasing the detector size is partially
due to the industry reliance on the approximate FDK algorithm
cite:pan_why_2009. For increasingly large cone angles at the ends of
the axial FOV, the approximation in the algorithm becomes increasingly
worse resulting in cone-angle artifacts cite:feldkamp_practical_1984.

Another problem with the current circular imaging trajectory is
potential linac collisions with the patient
cite:hua_practical_2004,nioutsikou_patient-specific_2003. Cases arise
when the patient is positioned in the treatment position, a CBCT image
cannot be acquired due to part of the patient being in the path of the
linac's trajectory. As the current FDK algorithm requires a trajectory
with sufficient angular coverage, the patient must be moved to a
position where the gantry can make an uninterrupted rotation around
the patient.

* Axial field-of-view extension
  :PROPERTIES:
  :ID:       eaae199f-f899-4862-af50-720895a31c36
  :END:
** notes                                     :noexport:
   :PROPERTIES:
   :ID:       7c250434-fff6-41a3-aea3-e7bc9ff88dc6
   :END:
- General approach seems to be to make the chapters presentations of
  different studies (papers/proceedings) and the subsequent results
  and conclusions that can be made.
*** publications
    :PROPERTIES:
    :ID:       48459222-20e7-43e5-9863-5022a5803a1b
    :END:
**** cite:davis_extended_2013
     :PROPERTIES:
     :ID:       5b4c7bca-d59b-4f33-8151-a6b359071249
     :END:
- simulation study of axial FOV extension
**** cite:davis_verifying_2013
     :PROPERTIES:
     :ID:       d4c20a7d-4982-4318-b591-9ff84ee809f5
     :END:
- Trilogy scans of RANDO and Defrise phantom for axial FOV extension
**** cite:pearson_investigation_2013
     :PROPERTIES:
     :ID:       6ae09b4c-d1d3-4705-b110-8a4a0e1f33dd
     :END:
- Similar results to [[id:d4c20a7d-4982-4318-b591-9ff84ee809f5][cite:davis_verifying_2013]] using RANDO and Defrise
  Trilogy scans
**** cite:davis_we-g-brf-07:_2014
     :PROPERTIES:
     :ID:       3f9687ce-f913-43a0-8e96-0ace96d7f67c
     :END:
- AAPM talk using CLLC scan from TrueBeam
**** cite:davis_su-e-i-02:_2015
     :PROPERTIES:
     :ID:       15f62bff-3fae-4083-b4b1-ad0594d25121
     :END:
- AAPM poster for disk phantom metrics
**** cite:davis_non-circular_2015
     :PROPERTIES:
     :ID:       cee07d24-100a-4c78-a42d-59cd707cda3b
     :END:
- Varian meeting showing non-circular scans
** Introduction
   :PROPERTIES:
   :ID:       b815fcd4-92c6-4f72-9905-10acc22b580e
   :END:

** Background
   :PROPERTIES:
   :ID:       f9e1fab3-973f-4ec3-b810-ba0f26e6f309
   :END:

** Methods
   :PROPERTIES:
   :ID:       b42e5e65-dfda-4692-8ea6-f6d96bc1dd5b
   :END:
*** Simulation
    :PROPERTIES:
    :ID:       6888683a-4d00-4cb2-be7e-8ac554af7595
    :END:
    Clinical extended-axial-FOV images are obtained by stitching
    together two circular scans at different axial locations. We first
    wanted to find the maximum axial coverage that can be achieved with
    such a trajectory. That is, what would be the maximum axial
    spacing between the two planes of the source's trajectory for
    which a useful extended volume image could be reconstructed?

    Simulating forward projections from this trajectory, we compared
    the images obtained from stitching together the independent FDK
    images to those obtained by reconstructing the two circles as a
    single trajectory with MLEM. We also compared stacked FDK images
    to reconstructions from the simulated *CLC* and smooth
    trajectories.

    We simulated a Defrise-style phantom modeled with the 3D X-ray
    projection software TAKE cite:seger_matlab/c_2005. The phantom was
    composed of a 15.2 cm outer diameter acrylic cylinder with
    alternating density disks of Delrin and cork 0.5 mm thick. This
    particular phantom with alternating density disks is acknowledged
    by the authors of FDK as being particularly susceptible to
    cone-angle artifacts cite:feldkamp_practical_1984.

    We used the TAKE software to forward project the phantom as well
    as generate a digitized "truth" phantom for calculating comparison
    metrics. The projector generates a forward projection from a
    specified trajectory given a mathematical definition of the
    phantom as well as its material properties and the spectrum
    generated by the x-ray source.

    We created projection data for a set of dual-circle trajectories
    that had an increasing amount of axial separation between the two
    circles. With a 1.5x magnification factor and a 30 cm detector
    size along the axial direction, a single circular scan has a
    maximum axial coverage of 20 cm in the image space. Furthermore,
    the maximum spacing between the two circles is 20 cm as any
    separation larger than this means the independent image volumes
    from the two circles are no longer contiguous. We therefore
    created trajectories with 10, 12, 14, 16, 18, and 20 cm
    separations *only show the larger gaps that are of interest?*
    between the planes of the source's dual-circle trajectory.

    We uniformly distributed 600 views over the entire trajectory
    which is comparable to the total number of views used in a single
    clinical CBCT scan with the kV imaging system. For the other two
    trajectories with a component of projection views taken during the
    axial translation (CLC and smooth), 600 views were used with 20% of
    the views being distributed along the axial translation stage.

    *FIX*

    The reconstruction image space consisted of a $256\times256$ transverse
    grid of 1 mm isotropic voxels. As the spacing between the circles
    increased, the number of voxels in the axial direction also
    increased to accommodate the increasingly large FOV.

    For the extended-volume reconstruction using the stacked FDK, we
    independently reconstructed each circular scan with FDK using a
    standard Hann filter. To combine the two reconstructed volumes for an
    extended axial-coverage image at a given spacing, we used the midplane
    between the two planes of the source's circular trajectory to select
    how much of each reconstruction to put in the combined image.

    For the MLEM reconstructions, we used all of the projection data
    simultaneously to reconstruct the extended volume. After defining the
    extended image volume, we computed the system matrix for each of the
    different spacings and trajectories based on the trajectory of the
    source and detector. We used 100 iterations *justify choice* of the
    MLEM algorithm to find an estimate for the image.


    *FIX*

    Our initial evaluation of the images obtained from non-circular
    trajectories is simply a qualitative visual inspection which does
    provide an informative assessment of the variety of artifacts that
    occur for a given reconstruction. For a more rigorous evaluation of
    the images obtained from different trajectories, we will use mutual
    information (MI) cite:pluim_mutual-information-based_2003 and the
    universal quality index (UQI) cite:wang_universal_2002 to provide a
    quantitative assessment of the image similarity between the reference
    image and the images from different trajectories.

** Results
   :PROPERTIES:
   :ID:       b2a353e8-8531-4a0e-8337-9f702ecf02f8
   :END:

** Conclusion
   :PROPERTIES:
   :ID:       99a861bc-c072-4082-806f-9279fa7c3a3c
   :END:

* Geometric calibration
  :PROPERTIES:
  :ID:       652970b8-4916-4190-b83b-2d6ae117c8b3
  :END:
** notes                                     :noexport:
   :PROPERTIES:
   :ID:       5c9cdd8b-721f-49b3-b136-c3282bf3659c
   :END:

- General approach seems to be to make the chapters presentations of
  different studies (papers/proceedings) and the subsequent results
  and conclusions that can be made.

** Introduction
   :PROPERTIES:
   :ID:       26feb0f0-f33e-4972-af9c-f73e0124f074
   :END:

** Background
   :PROPERTIES:
   :ID:       3fe1a782-94b5-4811-8b5f-d5089a578a6c
   :END:

** Methods
   :PROPERTIES:
   :ID:       0b636fe5-fe45-4f10-a5fc-2de8a82bfbe4
   :END:

** Results
   :PROPERTIES:
   :ID:       bc50c80a-fbb7-41d3-a9d0-ebc552f59896
   :END:

** Conclusion
   :PROPERTIES:
   :ID:       80e42b2c-5d4b-4646-91df-753802591344
   :END:

* Optimization-based algorithms
  :PROPERTIES:
  :ID:       06ec01f2-e128-4baf-9ec7-4569a3aaa886
  :END:
** notes                                                          :noexport:
   :PROPERTIES:
   :ID:       8ae68db5-8b7d-4458-ab2f-0e46b3b5beb4
   :END:

- General approach seems to be to make the chapters presentations of
  different studies (papers/proceedings) and the subsequent results
  and conclusions that can be made.

** Introduction
   :PROPERTIES:
   :ID:       8736adf3-2606-43c1-ba5d-d3f92a74f9f8
   :END:

** Background
   :PROPERTIES:
   :ID:       9bf44c0b-f3a4-4f5a-a73f-942944af351b
   :END:

** Methods
   :PROPERTIES:
   :ID:       f9ebfd7f-108b-4dd3-a24c-dab617ab99dd
   :END:

** Results
   :PROPERTIES:
   :ID:       04615b7c-c67c-499c-b2f9-d236ff743ea4
   :END:

** Conclusion
   :PROPERTIES:
   :ID:       0b2ab8ae-fd94-4d01-a7e0-8bef4db30078
   :END:

* Patient-specific trajectories
  :PROPERTIES:
  :ID:       99055e18-4b61-404e-9408-ebd5fd0a5d8d
  :END:
** notes                                     :noexport:
   :PROPERTIES:
   :ID:       53a46fd0-a854-4b6a-a253-dde04d4f7a87
   :END:
- General approach seems to be to make the chapters presentations of
  different studies (papers/proceedings) and the subsequent results
  and conclusions that can be made.
*** publications
    :PROPERTIES:
    :ID:       32703eae-6f65-4a6a-9f23-813e60747126
    :END:
- 2015 MIC virtual isocenter
- 2016 CT meeting dyanmic magnification
- 2016 MIC mixed magnification
** Introduction
   :PROPERTIES:
   :ID:       d5a22c7a-f72e-4a1c-b90f-69f7084d42e1
   :END:

** Background
   :PROPERTIES:
   :ID:       8e2b1082-311a-4c11-b3b2-22504451fbf0
   :END:

** Methods
   :PROPERTIES:
   :ID:       9d2ba9ad-7739-46ab-9983-754fa6adac28
   :END:

** Results
   :PROPERTIES:
   :ID:       a59ef4e0-4966-4c76-b283-5aea6b92360e
   :END:

** Conclusion
   :PROPERTIES:
   :ID:       8784656f-c169-410a-9a76-0454c6ab5dde
   :END:

* Summary and Conclusions
  :PROPERTIES:
  :ID:       1bade25b-80d6-4650-b8a3-baf370fa657c
  :END:

\makebibliography
